### ISSUE TITLE
training / finetune code?

### ISSUE THREAD

**Issue by hrcheng98** [jy0205/Pyramid-Flow#117]
Do you have plans to release the training and fine-tuning code in the future? Thanks.❤️

**Comment by jy0205** [comment]
The training (fine-tuning) code will be released next week. By the way, we recently switched to flux architecture and retrained the model from scratch to solve the human structure and face distortion problems due to the sd3 weights. We also plan to release the new checkpoint next week (first 384p version and then 768p version after finishing training). Stay tuned!

**Comment by andrearama** [comment]
Any news on when the training and flux models will be release? 

Thanks for the great work!

**Comment by jy0205** [comment]
Soon, we're almost done

**Comment by feifeiobama** [comment]
We have open-sourced the training code, please feel free to use them and report any issues :D
