### ISSUE TITLE
temp？

### ISSUE THREAD

**Issue by henbucuoshanghai** [jy0205/Pyramid-Flow#135]
temp=16: 5s, temp=31: 10s     
why？

**Comment by feifeiobama** [comment]
Thank you for your attention. This is due to the fact that we use a causal VAE similar to [MAGVIT-v2](https://arxiv.org/abs/2310.05737). It results in two types of latents (the first latent is exactly the same as an image, while the rest are video-specifc with a compression rate of 8). For example, a 10-second video with 241 frames is encoded as:

Time | 0s | 0s-5s | 5s-10s
-- | -- | -- | --
Video frame | 1st | 2nd-121th | 122th-241th
Latent frame | 1st | 2nd-16th | 17th-31th

**Comment by henbucuoshanghai** [comment]
In training process,how temp is used?
channel of Vae is16？how long vae
 is trained? 64 is better?

**Comment by feifeiobama** [comment]
1. In training, we use a progressive strategy, e.g. training on 5-second videos (temp=16) and then 10-second videos  (temp=31).
2. The number of channels in our VAE is indeed 16.
3. The VAE is trained on 32 A100 GPUs for about 3 days. By convention, this is not counted in the total training time.
4. Yes, there is a trend to use more channels because you can get better visual quality and even higher compression rate (see https://arxiv.org/abs/2410.10733).

**Comment by henbucuoshanghai** [comment]
nice and useful  answer, tks
