### ISSUE TITLE
Question about "frame_per_unit"

### ISSUE THREAD

**Issue by xujingUSTC** [jy0205/Pyramid-Flow#136]
Thanks for your amazing work!
I wonder how "frame_per_unit" is set during training, have you experimented with varying values for it during training, and can we run inference with different "frame_per_unit"?

**Comment by feifeiobama** [comment]
We implemented `frame_per_unit` in advance just in case the autoregressive model doesn't perform well in predicting the next single frame, so we might want it to predict multiple frames at once. In later experiments, however, we find that this is not necessary.

Since we just open-sourced the training code, please feel free to use it to test your ideas.
