### ISSUE TITLE
Causal > Casual typo

### ISSUE THREAD

**Issue by screan** [jy0205/Pyramid-Flow#2]
<img width="361" alt="Screenshot 2024-10-09 at 9 44 41 PM" src="https://github.com/user-attachments/assets/a76f111a-7106-4176-9791-8c4b076df0d9">

102 typos

**Comment by feifeiobama** [comment]
Thank you for your interest in our project. We would like to note that the spelling of "Causal" is correct as we use a causal VAE which is similar to [MAGVIT-v2](https://arxiv.org/abs/2310.05737). It is composed of causal convolutions, so that the output for each frame depends only on the previous frames.

Meanwhile, great thanks for pointing out another typo: `from .modeling_casual_vae import` should be changed to `from .modeling_causal_vae import`. We will fix this as soon as possible.

**Comment by feifeiobama** [comment]
The issue has been fixed in commit https://github.com/jy0205/Pyramid-Flow/commit/1b57a6a89bd6c3401fd9a408c456cdc7bef02469. Thanks for your contribution!
