### ISSUE TITLE
Some questions about the ar version and non-ar version

### ISSUE THREAD

**Issue by Aziily** [jy0205/Pyramid-Flow#207]
Thank you for your outstanding open-source contributions. Your work has made a significant impact, and I truly appreciate the value it brings to the community.

However, I have some questions about the AR part, as the Section 3.3 in the paper.

1. It seems that when using AR to inference, the computing consumption is larger than the original one, because each feature frame is required to be calculated individually. Is this correct or I make some mistakes?

2. Whether the AR design leads to some improvements in the performance or just for the adaption of I2V?

3. Will you share a checkpoint without AR in the future?

Thanks again.

**Comment by feifeiobama** [comment]
1. There is indeed some redundant inference computation in predicting each frame separately, but the total computation is less than the original one because we have designed a careful history compression scheme that dramatically reduces the number of tokens.
  <img width="362" alt="image" src="https://github.com/user-attachments/assets/9f2229fb-d2f4-4046-8812-2ac24dbe40cf">

2. The AR design (with history compression) is the main reason for our high training efficiency. It improves the performance as shown in Figure 8. We also have some new quantitative comparisons:
  <img width="365" alt="image" src="https://github.com/user-attachments/assets/8a58fcac-6d2a-4662-aea7-8e359b33d3cc">

3. We do not have the checkpoint without AR, as it is only trained for a few steps due to limited computing resources.

**Comment by Aziily** [comment]
So the full-seq diffusion in the second graph means a parallel diffusion or a AR diffusion?

I tested time consumption in inference with AR and without AR. It seems to be a great difference, 67.04 (640 x 384 x 121 with AR) and 51.42 (same resolution without AR). I think there may be some potential in efficiency if pipeline without AR also works well.

**Comment by feifeiobama** [comment]
Thank you for sharing the insight. Full-seq diffusion means parallel diffusion using the spatial pyramid (without AR/temporal pyramid). We also believe that it alone has the potential in terms of inference efficiency and generation stability, and will continue to explore both AR and non-AR approaches.
