### ISSUE TITLE
实际测试3秒以后效果开始变差，后续是否有优化计划？

### ISSUE THREAD

**Issue by aigcchumen** [jy0205/Pyramid-Flow#27]
https://github.com/user-attachments/assets/c2445e46-ea45-459a-83d2-ff7c1265ec16

**Comment by feifeiobama** [comment]
Yes, we have an ongoing optimization plan by training the model from scratch instead of using the SD3 weight initialization. This seems to improve the human structure (face, body) in our early experiments for images. Meanwhile, we need more research efforts to improve the temporal stability in the autoregressive video generation.

**Comment by jy0205** [comment]
Maybe you can reduce the `video_guidance_scale` to a lower value (e.g., 3.0 or 2.0). A higher `video_guidance_scale` may encourage large-scale motion but will cause visual quality degradation. A smaller `video_guidance_scale` will produce more stable video content (relatively smaller motion).

**Comment by feifeiobama** [comment]
Closed as the miniFLUX checkpoint has been released.
