### ISSUE TITLE
Receiving burned results from image to video demo

### ISSUE THREAD

**Issue by OmerMachluf** [jy0205/Pyramid-Flow#28]
Let me start by saying kudos! the paper looks amazing, and the results you shared are incredible.
Thanks for sharing this with the community!.
I am trying out the notebook demo of image to video, and i'm running into several issues.
I am using all default parameters, with temp=16.
1. It looks like the result shape is torch.Size([1, 16, 17, 96, 160]), which means it generated a total of 17 frames, althought temp=16 is expected to generate 5 seconds video. i assume this has to do with frame_per_unit defaulted to 1?(and not overriden in demo?)
2. Trying to decode the results directly  of all frames by the VAE, i'm getting OOM on A6000, even with memory save option. it looks like it's trying to allocate unreasonable amounts of vram to do so: 
"OutOfMemoryError: CUDA out of memory. Tried to allocate 63.28 GiB. GPU 0 has a total capacity of 47.51 GiB of which 5.34 GiB is free"
3. And most importantly, while i'm able to overcome the issue in (2) by decoding it frame by frame, the results are 'burned': 
![image](https://github.com/user-attachments/assets/6478fe69-0f80-4120-8c59-9def185c6b55)

Would appreciate your help in understanding how to resolve those issues :)

**Comment by feifeiobama** [comment]
You mentioned that "Trying to decode the results directly of all frames by the VAE", may I ask if you are using a different VAE decoding strategy from ours?
https://github.com/jy0205/Pyramid-Flow/blob/bdc3de990b39bb1a8cc6ff48a1d2d7f01ae5c9ee/pyramid_dit/pyramid_dit_for_video_gen_pipeline.py#L662-L667

In the above decoding function, we use different means and stds for the first latent and the following 16 latents. Therefore, it may cause a burned effect if a simple decoding strategy is used. This is due to the fact that we use a causal VAE similar to [MAGVIT-v2](https://arxiv.org/abs/2310.05737). It results in two types of latents (the first latent is exactly the same as an image, while the rest are video-specific), so they need to be normalized separately.

**Comment by OmerMachluf** [comment]
Thanks for the quick response!
this is probably the cause for the burning effect and i will test it out soon.
The reason i was trying to decode it frame by frame was because I couldn't get the vae tod ecode it all in once without recieving OOM

**Comment by jy0205** [comment]
You can set `save_memory=True`. If the decoding memory still exceeds, you can reduce the `tile_sample_min_size` here from 256 to 128.
https://github.com/jy0205/Pyramid-Flow/blob/bdc3de990b39bb1a8cc6ff48a1d2d7f01ae5c9ee/pyramid_dit/pyramid_dit_for_video_gen_pipeline.py#L671

**Comment by OmerMachluf** [comment]
When running the text to image demo before trying the image to video demo everything works great. i guess this is about the vae tiling being enabled in the text to video cell but not in the image to video cell :)

**Comment by feifeiobama** [comment]
Thank you for the feedback. We have moved the `vae.enable_tiling()` function to the initialization block in https://github.com/jy0205/Pyramid-Flow/commit/5d85625f16d8807502ceac654e9f5f34460c47c6.

> When running the text to image demo before trying the image to video demo everything works great. i guess this is about the vae tiling being enabled in the text to video cell but not in the image to video cell :)
