### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by Infogaia** [jy0205/Pyramid-Flow#54]
First of all I apreciate the great work! 

I have some questions regarding the speed of my generations and if they can be improved, or maybe I am doing something wrong.

My specs:
RTX 4070ti 12GB
32 GB RAM

I produced a 5s video with the 768p model in about 20 mins. Is that in the "normal" range?
I had CPU offloading enabled.

Also I noticed that the first iterations were much faster than the last ones. Additionally, GPU Power dropped from -200W to around 70W also GPU Memory maxed at 99% after i = 10 or so. Can anybody explain to me what can be done do improve or what I am not understanding.

Thanks for your help

**Comment by feifeiobama** [comment]
It is in the "normal" range, which is consistent with https://github.com/jy0205/Pyramid-Flow/pull/23#issuecomment-2406223821 and https://github.com/jy0205/Pyramid-Flow/pull/23#issuecomment-2408291089.

The other two phenomena you noticed are also reasonable. 1. "the first iterations were much faster than the last ones" is due to the increasing token length in autoregressive generation. 2. The GPU power drop is because we enter the VAE decoding stage after DiT generation. You can reduce its memory usage by following https://github.com/jy0205/Pyramid-Flow/issues/5#issuecomment-2404445996
