### ISSUE TITLE
Issues about training data

### ISSUE THREAD

**Issue by Zefan-Cai** [jy0205/Pyramid-Flow#80]
What is the data used in the final stage - high-resolution training>

**Comment by feifeiobama** [comment]
We use a mixed corpse of videos and images in the final stage training. The videos include [OpenVid-1M](https://huggingface.co/datasets/nkp37/OpenVid-1M), [Open-Sora Plan v1.0.0](https://huggingface.co/datasets/LanguageBind/Open-Sora-Plan-v1.0.0), [Open-Sora Plan v1.1.0](https://huggingface.co/datasets/LanguageBind/Open-Sora-Plan-v1.1.0) and some small public datasets mentioned in [Open-Sora](https://github.com/hpcaitech/Open-Sora/blob/main/docs/datasets.md). The images include a subset of non-blurred [SA-1B](https://ai.meta.com/datasets/segment-anything-downloads/), [LAION-Aesthetics 6.5+](https://huggingface.co/datasets/bhargavsdesai/laion_improved_aesthetics_6.5plus_with_images), [Upsplash-lite](https://github.com/unsplash/datasets) and two MidJourney synthetic datasets ([v6](https://huggingface.co/datasets/terminusresearch/midjourney-v6-520k-raw), [v5](https://huggingface.co/datasets/wanng/midjourney-v5-202304-clean)).

**Comment by Zefan-Cai** [comment]
So do you do image training in the third stage? I mistakenly thought that the third stage is only about video.

**Comment by Zefan-Cai** [comment]
And have you considered using Open-Sora Plan v 1.2.0? It seems like the Panda70m and pexel used in OpenSora v1.2.0 are also high-quality. Have you considered using that>

**Comment by feifeiobama** [comment]
> And have you considered using Open-Sora Plan v 1.2.0? It seems like the Panda70m and pexel used in OpenSora v1.2.0 are also high-quality. Have you considered using that>

**Panda70M**: we didn't use them for two reasons: 1) Quality & length: they are relatively short and contain many noisy videos. 2) Youtube download: since our last work [Video-LaVIT](https://video-lavit.github.io), our server address in Kuaishou has been blocked by YouTube, so we cannot download these videos. Because of this, we also couldn't download some amazing public datasets like [MiraData](https://mira-space.github.io).

**Pexels**: we already used Pexels since it is included in Open-Sora Plan v1.0.0, we believe that including more of these data will certainly improve the model performance.

**Comment by feifeiobama** [comment]
> So do you do image training in the third stage? I mistakenly thought that the third stage is only about video.

We distribute videos and images on different GPUs, I remember that videos use 120 GPUs and images use 8 GPUs. This part is actually done by my co-author and my answer may be wrong. If so, I will edit the answer later.

**Comment by Zefan-Cai** [comment]
> > So do you do image training in the third stage? I mistakenly thought that the third stage is only about video.
> 
> We distribute videos and images on different GPUs, I remember that videos use 120 GPUs and images use 8 GPUs. This part is actually done by my co-author @jy0205 and my answer may be wrong. If so, I will edit the answer later.

So is it necessary to have a mix of image and Video training in the third stage? Would there be anything bad if we only train on video?

**Comment by Zefan-Cai** [comment]
And I am also curious about whether there can also be a new stage to train the model from 768 to 1080 and from 10s to 20s? Can you infinitely extend the model capacity by infinite training stage extension?

**Comment by feifeiobama** [comment]
> > > So do you do image training in the third stage? I mistakenly thought that the third stage is only about video.
> > 
> > 
> > We distribute videos and images on different GPUs, I remember that videos use 120 GPUs and images use 8 GPUs. This part is actually done by my co-author @jy0205 and my answer may be wrong. If so, I will edit the answer later.
> 
> So is it necessary to have a mix of image and Video training in the third stage? Would there be anything bad if we only train on video?

No, I think it is not. The purpose of including images is mostly to improve visual aesthetics. Meanwhile, frames from the video are more realistic and therefore better for realistic video generation.

**Comment by Zefan-Cai** [comment]
> > > > So do you do image training in the third stage? I mistakenly thought that the third stage is only about video.
> > > 
> > > 
> > > We distribute videos and images on different GPUs, I remember that videos use 120 GPUs and images use 8 GPUs. This part is actually done by my co-author @jy0205 and my answer may be wrong. If so, I will edit the answer later.
> > 
> > 
> > So is it necessary to have a mix of image and Video training in the third stage? Would there be anything bad if we only train on video?
> 
> No, I think it is not. The purpose of including images is mostly to improve visual aesthetics. Meanwhile, frames from the video are more realistic and therefore better for realistic video generation.

Thanks for your timely reply!

**Comment by feifeiobama** [comment]
> And I am also curious about whether there can also be a new stage to train the model from 768 to 1080 and from 10s to 20s? Can you infinitely extend the model capacity by infinite training stage extension?

We have very few long videos (e.g. >5s), since most high-resolution videos from OpenVid-1M are much shorter. In fact, you can see that the model is relatively more stable in the early generation process <5s. It may not be feasible to extend the training process to longer videos using the current datasets. However, it is possible if you have access to long-duration high-resolution video datasets (e.g. MiraData).

**Comment by honestabelink** [comment]
@feifeiobama We have a dataset currently around 1M videos from major social media company. We're expanding by 10M each month for the next 10 months, totaling 100M vidoes.

If we could be of assistance to you feel free to reach out. We'll provide no-cors links, the dataset can be quickly downloaded.

You can reach me directly at :
Email : honestabelink@openroot-compute.org
Discord : honestabelink

Thanks for your work.

**Comment by feifeiobama** [comment]
> @feifeiobama We have a dataset currently around 1M videos from major social media company. We're expanding by 10M each month for the next 10 months, totaling 100M vidoes.
> 
> If we could be of assistance to you feel free to reach out. We'll provide no-cors links, the dataset can be quickly downloaded.
> 
> You can reach me directly at : Email : [honestabelink@openroot-compute.org](mailto:honestabelink@openroot-compute.org) Discord : honestabelink
> 
> Thanks for your work.

Thank you for your kind help. Since our current priority is in addressing human deformation & temporal degradation issues, we will contact you as soon as they are fixed.

**Comment by honestabelink** [comment]
> Since our current priority is in addressing human deformation & temporal degradation issues, we will contact you as soon as they are fixed.

Sounds good, we'll be working hard to have data ready for you. Our dataset primarily focuses on human, all ages and all genders, other categories are easy to recovery from current public datasets. Typical video is >15 secs, and portrait aspect ratio.

We're also looking into contracting out a recovery model for video, think [SUPIR](https://supir.xpixel.group/) but for video. Particularly we need a diffusion based solution for motion blur. Typical degradation is solved, low light, compression artifacts, etc. But, no available model handles motion artifacts. This would greatly extend the trainable set of data before a final fine-tune on real data.

Low quality example, motion artifacts are preserved due to deficiencies in the training data.
![image](https://github.com/user-attachments/assets/267e65d4-e609-4208-be51-bcb84ba4a343)

We have extremely high quality video to address this, we're looking for a partner to work with in this area too.

Thanks for your considerations.
