### ISSUE TITLE
prompting style

### ISSUE THREAD

**Issue by ptits** [jy0205/Pyramid-Flow#90]
should it be more natural text like for SD3 and Flux (due to DiT)?
or it has been trained on oldschool danburu tags and shamanic language of SD1.5 and we need to use all this 1girl, artstation and so on

**Comment by feifeiobama** [comment]
I suppose short natural text is more suitable. This is due to (1) we use T5 text encoder as in SD3 and FLUX so it supports natural text well. (2) during recaptioning, we set our recaptioner (Video-LLaMA2) to produce short natural caption without tags.

That being said, since we used some image dataset where  the caption may not look like natural text (e.g. MidJourney synthetic dataset), our model may work better with proper tags. I am not a prompting expert and haven't tested the effect of those tags.

**Comment by ptits** [comment]
thanks for reply
I will make more tests

it looks like model TRIES to understand natural language but is very dependent to dataset
